# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

In [28]:
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

### Step 3. Assign it to a variable called iris

In [14]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris=pd.read_csv(url)

In [15]:
iris.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

### Step 4. Create columns for the dataset

In [18]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class
iris.columns=['sepal_length','sepal_width (in cm)','petal_length','petal_width','class']

In [19]:
iris.head()

   sepal_length  sepal_width (in cm)  petal_length  petal_width        class
0           4.9                  3.0           1.4          0.2  Iris-setosa
1           4.7                  3.2           1.3          0.2  Iris-setosa
2           4.6                  3.1           1.5          0.2  Iris-setosa
3           5.0                  3.6           1.4          0.2  Iris-setosa
4           5.4                  3.9           1.7          0.4  Iris-setosa

### Step 5.  Is there any missing value in the dataframe?

In [21]:
#iris.isnull()
pd.isnull(iris).sum

<bound method DataFrame.sum of      sepal_length  sepal_width (in cm)  petal_length  petal_width  class
0           False                False         False        False  False
1           False                False         False        False  False
2           False                False         False        False  False
3           False                False         False        False  False
4           False                False         False        False  False
5           False                False         False        False  False
6           False                False         False        False  False
7           False                False         False        False  False
8           False                False         False        False  False
9           False                False         False        False  False
10          False                False         False        False  False
11          False                False         False        False  False
12          False                False         False        False  False
13          False                False         False        False  False
14          False                False         False        False  False
15          False                False         False        False  False
16          False                False         False        False  False
17          False                False         False        False  False
18          False                False         False        False  False
19          False                False         False        False  False
20          False                False         False        False  False
21          False                False         False        False  False
22          False                False         False        False  False
23          False                False         False        False  False
24          False                False         False        False  False
25          False                False         False        False  False
26          False                False         False        False  False
27          False                False         False        False  False
28          False                False         False        False  False
29          False                False         False        False  False
..            ...                  ...           ...          ...    ...
119         False                False         False        False  False
120         False                False         False        False  False
121         False                False         False        False  False
122         False                False         False        False  False
123         False                False         False        False  False
124         False                False         False        False  False
125         False                False         False        False  False
126         False                False         False        False  False
127         False                False         False        False  False
128         False                False         False        False  False
129         False                False         False        False  False
130         False                False         False        False  False
131         False                False         False        False  False
132         False                False         False        False  False
133         False                False         False        False  False
134         False                False         False        False  False
135         False                False         False        False  False
136         False                False         False        False  False
137         False                False         False        False  False
138         False                False         False        False  False
139         False                False         False        False  False
140         False                False         False        False  False
141         False                False         False        False  False
142         False                False         False        False  False
143         False                False         False        False  False
144         False                False         False        False  False
145         False                False         False        False  False
146         False                False         False        False  False
147         False                False         False        False  False
148         False                False         False        False  False

[149 rows x 5 columns]>

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [30]:
iris[10:29]['petal_length']=np.NAN

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
iris[10:29]

    sepal_length  sepal_width (in cm)  petal_length  petal_width        class
10           4.8                  3.4           NaN          0.2  Iris-setosa
11           4.8                  3.0           NaN          0.1  Iris-setosa
12           4.3                  3.0           NaN          0.1  Iris-setosa
13           5.8                  4.0           NaN          0.2  Iris-setosa
14           5.7                  4.4           NaN          0.4  Iris-setosa
15           5.4                  3.9           NaN          0.4  Iris-setosa
16           5.1                  3.5           NaN          0.3  Iris-setosa
17           5.7                  3.8           NaN          0.3  Iris-setosa
18           5.1                  3.8           NaN          0.3  Iris-setosa
19           5.4                  3.4           NaN          0.2  Iris-setosa
20           5.1                  3.7           NaN          0.4  Iris-setosa
21           4.6                  3.6           NaN          0.2  Iris-setosa
22           5.1                  3.3           NaN          0.5  Iris-setosa
23           4.8                  3.4           NaN          0.2  Iris-setosa
24           5.0                  3.0           NaN          0.2  Iris-setosa
25           5.0                  3.4           NaN          0.4  Iris-setosa
26           5.2                  3.5           NaN          0.2  Iris-setosa
27           5.2                  3.4           NaN          0.2  Iris-setosa
28           4.7                  3.2           NaN          0.2  Iris-setosa

### Step 7. Good, now lets substitute the NaN values to 1.0

In [32]:
iris.fillna(1.0)

,sepal_length,sepal_width (in cm),petal_length,petal_width,class
0,4.9,3.0,1.4,0.2,Iris-setosa
1,4.7,3.2,1.3,0.2,Iris-setosa
2,4.6,3.1,1.5,0.2,Iris-setosa
3,5.0,3.6,1.4,0.2,Iris-setosa
4,5.4,3.9,1.7,0.4,Iris-setosa
5,4.6,3.4,1.4,0.3,Iris-setosa
6,5.0,3.4,1.5,0.2,Iris-setosa
7,4.4,2.9,1.4,0.2,Iris-setosa
8,4.9,3.1,1.5,0.1,Iris-setosa
9,5.4,3.7,1.5,0.2,Iris-setosa
10,4.8,3.4,1.0,0.2,Iris-setosa
11,4.8,3.0,1.0,0.1,Iris-setosa
12,4.3,3.0,1.0,0.1,Iris-setosa
13,5.8,4.0,1.0,0.2,Iris-setosa
14,5.7,4.4,1.0,0.4,Iris-setosa
15,5.4,3.9,1.0,0.4,Iris-setosa
16,5.1,3.5,1.0,0.3,Iris-setosa
17,5.7,3.8,1.0,0.3,Iris-setosa
18,5.1,3.8,1.0,0.3,Iris-setosa
19,5.4,3.4,1.0,0.2,Iris-setosa
20,5.1,3.7,1.0,0.4,Iris-setosa
21,4.6,3.6,1.0,0.2,Iris-setosa
22,5.1,3.3,1.0,0.5,Iris-setosa
23,4.8,3.4,1.0,0.2,Iris-setosa
24,5.0,3.0,1.0,0.2,Iris-setosa
25,5.0,3.4,1.0,0.4,Iris-setosa
26,5.2,3.5,1.0,0.2,Iris-setosa
27,5.2,3.4,1.0,0.2,Iris-setosa
28,4.7,3.2,1.0,0.2,Iris-setosa
29,4.8,3.1,1.6,0.2,Iris-setosa
...,...,...,...,...,...
119,6.9,3.2,5.7,2.3,Iris-virginica
120,5.6,2.8,4.9,2.0,Iris-virginica
121,7.7,2.8,6.7,2.0,Iris-virginica
122,6.3,2.7,4.9,1.8,Iris-virginica
123,6.7,3.3,5.7,2.1,Iris-virginica
124,7.2,3.2,6.0,1.8,Iris-virginica
125,6.2,2.8,4.8,1.8,Iris-virginica
126,6.1,3.0,4.9,1.8,Iris-virginica
127,6.4,2.8,5.6,2.1,Iris-virginica
128,7.2,3.0,5.8,1.6,Iris-virginica
129,7.4,2.8,6.1,1.9,Iris-virginica
130,7.9,3.8,6.4,2.0,Iris-virginica
131,6.4,2.8,5.6,2.2,Iris-virginica
132,6.3,2.8,5.1,1.5,Iris-virginica
133,6.1,2.6,5.6,1.4,Iris-virginica
134,7.7,3.0,6.1,2.3,Iris-virginica
135,6.3,3.4,5.6,2.4,Iris-virginica
136,6.4,3.1,5.5,1.8,Iris-virginica
137,6.0,3.0,4.8,1.8,Iris-virginica
138,6.9,3.1,5.4,2.1,Iris-virginica
139,6.7,3.1,5.6,2.4,Iris-virginica
140,6.9,3.1,5.1,2.3,Iris-virginica
141,5.8,2.7,5.1,1.9,Iris-virginica
142,6.8,3.2,5.9,2.3,Iris-virginica
143,6.7,3.3,5.7,2.5,Iris-virginica
144,6.7,3.0,5.2,2.3,Iris-virginica
145,6.3,2.5,5.0,1.9,Iris-virginica
146,6.5,3.0,5.2,2.0,Iris-virginica
147,6.2,3.4,5.4,2.3,Iris-virginica
148,5.9,3.0,5.1,1.8,Iris-virginica

### Step 8. Now let's delete the column class

In [33]:
del iris['class']

In [35]:
iris.head()

   sepal_length  sepal_width (in cm)  petal_length  petal_width
0           4.9                  3.0           1.4          0.2
1           4.7                  3.2           1.3          0.2
2           4.6                  3.1           1.5          0.2
3           5.0                  3.6           1.4          0.2
4           5.4                  3.9           1.7          0.4

### Step 9.  Set the first 3 rows as NaN

In [38]:
iris[0:3]=np.NAN

In [39]:
iris.head()

   sepal_length  sepal_width (in cm)  petal_length  petal_width
0           NaN                  NaN           NaN          NaN
1           NaN                  NaN           NaN          NaN
2           NaN                  NaN           NaN          NaN
3           5.0                  3.6           1.4          0.2
4           5.4                  3.9           1.7          0.4

### Step 10.  Delete the rows that have NaN

In [44]:
iris.dropna(inplace=True)

In [45]:
iris.head()

   sepal_length  sepal_width (in cm)  petal_length  petal_width
3           5.0                  3.6           1.4          0.2
4           5.4                  3.9           1.7          0.4
5           4.6                  3.4           1.4          0.3
6           5.0                  3.4           1.5          0.2
7           4.4                  2.9           1.4          0.2

### Step 11. Reset the index so it begins with 0 again

In [46]:
iris.reset_index(drop=True)

     sepal_length  sepal_width (in cm)  petal_length  petal_width
0             5.0                  3.6           1.4          0.2
1             5.4                  3.9           1.7          0.4
2             4.6                  3.4           1.4          0.3
3             5.0                  3.4           1.5          0.2
4             4.4                  2.9           1.4          0.2
5             4.9                  3.1           1.5          0.1
6             5.4                  3.7           1.5          0.2
7             4.8                  3.1           1.6          0.2
8             5.4                  3.4           1.5          0.4
9             5.2                  4.1           1.5          0.1
10            5.5                  4.2           1.4          0.2
11            4.9                  3.1           1.5          0.1
12            5.0                  3.2           1.2          0.2
13            5.5                  3.5           1.3          0.2
14            4.9                  3.1           1.5          0.1
15            4.4                  3.0           1.3          0.2
16            5.1                  3.4           1.5          0.2
17            5.0                  3.5           1.3          0.3
18            4.5                  2.3           1.3          0.3
19            4.4                  3.2           1.3          0.2
20            5.0                  3.5           1.6          0.6
21            5.1                  3.8           1.9          0.4
22            4.8                  3.0           1.4          0.3
23            5.1                  3.8           1.6          0.2
24            4.6                  3.2           1.4          0.2
25            5.3                  3.7           1.5          0.2
26            5.0                  3.3           1.4          0.2
27            7.0                  3.2           4.7          1.4
28            6.4                  3.2           4.5          1.5
29            6.9                  3.1           4.9          1.5
..            ...                  ...           ...          ...
97            6.9                  3.2           5.7          2.3
98            5.6                  2.8           4.9          2.0
99            7.7                  2.8           6.7          2.0
100           6.3                  2.7           4.9          1.8
101           6.7                  3.3           5.7          2.1
102           7.2                  3.2           6.0          1.8
103           6.2                  2.8           4.8          1.8
104           6.1                  3.0           4.9          1.8
105           6.4                  2.8           5.6          2.1
106           7.2                  3.0           5.8          1.6
107           7.4                  2.8           6.1          1.9
108           7.9                  3.8           6.4          2.0
109           6.4                  2.8           5.6          2.2
110           6.3                  2.8           5.1          1.5
111           6.1                  2.6           5.6          1.4
112           7.7                  3.0           6.1          2.3
113           6.3                  3.4           5.6          2.4
114           6.4                  3.1           5.5          1.8
115           6.0                  3.0           4.8          1.8
116           6.9                  3.1           5.4          2.1
117           6.7                  3.1           5.6          2.4
118           6.9                  3.1           5.1          2.3
119           5.8                  2.7           5.1          1.9
120           6.8                  3.2           5.9          2.3
121           6.7                  3.3           5.7          2.5
122           6.7                  3.0           5.2          2.3
123           6.3                  2.5           5.0          1.9
124           6.5                  3.0           5.2          2.0
125           6.2                  3.4           5.4          2.3
126           5.9                  3.0           5.1          1.8

[127 rows x 4 columns]